SEND_FILE_MAX_AGE_DEFAULT = 1
SQLALCHEMY_DATABASE_URI = "sqlite://"
VAPID_PRIVATE_KEY = "I8qUcwlSoGbkmGYzuz6wCAzF1Yh5PgbT82wIK9lQ8zw"
VAPID_CLAIM_EMAIL = "test@test.com"
# Public Key:
VAPID_PUBLIC_KEY = "BF6Hp95x3ipGgsv3MIpvrA67hsZtmDJs2pP_Fd_RpCXwZkkpMEFH6JEQ_OKZ3zZ4WbpDwvuKhh152pd08mnOQZg"

# Private Key:
